service: graphql-vault

custom:
  dbTable: ${self:service}-${self:provider.stage}
  output:
    file: stack-output.json
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - { "Fn::GetAtt": ["DbTable", "Arn" ] }

functions:
  graphql:
    handler: src/handler.graphql
    environment:
      DB_TABLE: ${self:custom.dbTable}
    events:
      - http:
          path: graphql
          method: GET

resources:
  Outputs:
    DbTableName:
      Description: "Db Table Name"
      Value:
        Ref: DbTable
  Resources:
    DbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: key
            AttributeType: S
        KeySchema:
          -
            AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: '${self:custom.dbTable}'
